config/routes.rb
Rails.application.routes.draw do
  root 'bioinfo#about'
  get 'bioinfo/about'
  get 'bioinfo/contact'
  get 'bioinfo/contact_details'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bioinfo_controller.rb
class BioinfoController < ApplicationController
  def about
  end
  def contact
  end  
  def contact_details
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    respond_to do |format|
      format.js   { render :layout => false }
    end
  end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bioinfo_helper.rb
module BioinfoHelper
end

app/views/bioinfo/about.html.haml
%font{:size => "6" , :color => "#E7746F"} About Me

.container-new
  %h1 I am an open source developer with hands on experience in ROR.
.container-new
  %h1 I love developing restfull web services and trying out new programming languages,tools,frameworks etc.
.container-resume
  Download My Complete Resume Here

app/views/bioinfo/contact.html.haml
%font{:size => "6" , :color => "#E7746F"} Contact Details
= form_tag(bioinfo_contact_details_path, method: 'get', :remote => true) do 
  = label_tag(:name, "Name:")
  &nbsp; 
  %input{:name => "name", :type => "text" , :required => true}
  %br/
  %br
  = label_tag(:email, "Email:")
  &nbsp; 
  %input{:name => "email", :type => "text" , :required => true}
  %br/
  %br
  = label_tag(:message, "Message:")
  &nbsp; 
  %textarea{name: 'message' , :cols => "40", :rows => "3" , :required => true}
  %br/
  %br
  = submit_tag("Submit")
  %br
  %br
  #details_div
    %table{border: '1'}
      %tr
        %th Name
        %th Email
        %th Message
      %tr
        %td#n
        %td#e
        %td#m
:javascript
  $(document).ready(function() {
    $('#contact_link').addClass('selected');
    $('#about_link').removeClass('selected');    

  });


  

app/views/bioinfo/contact_details.js.haml
$('#n').text("#{@name}");
$('#e').text("#{@email}");
$('#m').text("#{@message}");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Niketa_Biodata
    %meta{:content => "website description", :name => "description"}/
    %meta{:content => "website keywords, website keywords", :name => "keywords"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}/
    = stylesheet_link_tag "custom"
    = javascript_include_tag 'application'
  %body
    #main
      #header
        #logo
          #logo_text
            / class="logo_colour", allows you to change the colour of the text
            %h1
              Niketa Sharma
            %h2.logo_colour Software Developer
        = render 'partial/menu'
      #content_header
      #site_content
        #banner
        = yield
      #content_footer
      #footer
        %p
          Copyright © 2018| Niketa Sharma

app/views/partial/_menu.html.haml
#menubar
  %ul#menu
    %li#about_link.selected= link_to "About", bioinfo_about_path
    %li#contact_link= link_to "Contact", bioinfo_contact_path